---
title: "data preparation"
author: "omidalam"
date: "7/9/2020"
output: html_document
---

```{r setup, include=FALSE}
library(TSAtools)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(grid)
library(dplyr)
library(karyoploteR)

col= c(k562=I("#1b9e77"),
       hct= I("#d95f02"),
       hff= I("#7570b3"),
       h1=  I("#e7298a"))
```

## Task list
1a.  Replot using genomic percentile rather than scores- as I remember it will be much more linear for K562.
  - What is percentile normalization?
```{r}
# import and rebin in one go
import_rebin = function(path,bin,only_mcol=TRUE){
  bw = as.gr(path,genome = "hg38")
  bw = BW_bnr(bw,bin)
  if (only_mcol)
    mcols(bw)
  else bw
}
```
```{r}
# data prep 
# file pathes that i'm using here
bw_path=list(
  rep1=c(k562_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/TSA_Seq/25kb/K562_SON_TSA_25kb_hg38_rep1_201911condE.bw",
       k562_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/TSA_Seq/25kb/K562_LMNB_TSA_25kb_hg38_rep1_201508condA.bw",
       hct_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_SON_TSA_25kb_hg38_rep1_201711condE.bw",
       hct_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_LMNB1_TSA_25kb_hg38_rep1_201806condA.bw",
       hct_mki67 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_MKI67IP_TSA_25kb_hg38_rep1_201907condC.bw",
       hct_pol1 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_PolR1E_TSA_25kb_hg38_rep1_201903condC.bw",
       hct_ddx18 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_DDX18_TSA_25kb_hg38_rep1_201903condC.bw",
       
       hff_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/TSA_Seq/25kb/HFFc6_SON_TSA_25kb_hg38_rep1_201806condE.bw",
       hff_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/TSA_Seq/25kb/HFFc6_LMNB1_TSA_25kb_hg38_rep1_201810condAI.bw",
       
       h1_son = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/TSA_Seq/25kb/H1_SON_TSA_25kb_hg38_rep1_201807condE.bw",
       h1_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/TSA_Seq/25kb/H1_LMNB1_TSA_25kb_hg38_rep1_201810condAI.bw"),
  
  rep2=c(k562_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/TSA_Seq/25kb/K562_SON_TSA_25kb_hg38_rep2_201610condE.bw",
       k562_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/TSA_Seq/25kb/K562_LMNB_TSA_25kb_hg38_rep1_201712condA.bw",
       hct_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_SON_TSA_25kb_hg38_rep2_201803condE.bw",
       hct_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/TSA_Seq/25kb/HCT116_LMNB1_TSA_25kb_hg38_rep2_201806condA.bw",
       hff_son="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/TSA_Seq/25kb/HFFc6_SON_TSA_25kb_hg38_rep2_201711condE.bw",
       hff_lmnb="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/TSA_Seq/25kb/HFFc6_LMNB1_TSA_25kb_hg38_rep2_201810condAI.bw",
       h1_son = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/TSA_Seq/25kb/H1_SON_TSA_25kb_hg38_rep2_201807condE.bw",
       h1_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/TSA_Seq/25kb/H1_LMNB1_TSA_25kb_hg38_rep2_201903condAI.bw"),
  
  damID=c(
    k562_dam_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/DamID/25kb/K562_LMNB1_DAMID_25kb_hg38_combined.bw",
    k562_dam_ap3 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/k562/DamID/25kb/K562_4xAP3_DAMID_25kb_hg38_combined.bw",
    hct_dam_ap3 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/DamID/25kb/HCT116_4xAP3_DAMID_25kb_hg38_combined.bw", 
    hct_dam_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/DamID/25kb/HCT116_LMNB1_DAMID_25kb_hg38_combined.bw",
    hct_dam_ap3 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/DamID/25kb/HCT116_4xAP3_DAMID_25kb_hg38_combined.bw",
    hff_dam_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/DamID/25kb/HFF_LMNB1_DAMID_25kb_hg38_combined.bw",
    hff_dam_ap3 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hff/DamID/25kb/HFF_4xAP3_DAMID_25kb_hg38_combined.bw",
    h1_dam_lmnb = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/DamID/25kb/H1_LMNB1_DAMID_25kb_hg38_combined.bw",
    h1_dam_ap3 = "~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/h1esc/DamID/25kb/H1_4xAP3_DAMID_25kb_hg38_combined.bw"),
  hct_hist=c(
    h3k4me1="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/chip_seq_yang/HCT116_H3K4me1_ENCODE.Broad_ENCSR161MXP.bw",
    h3k4me3="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/chip_seq_yang/HCT116_H3K4me3_ENCODE.Broad_ENCSR333OPW.bw",
    h3k9me3="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/chip_seq_yang/HCT116_H3K9me3_ENCODE.Broad_ENCSR179BUC.bw",
    h3k27me3="~/box_sync/Andy_lab/Projects/U54_student_meeting/summary_paper/reference_data/hct116/chip_seq_yang/HCT116_H3K27me3_ENCODE.Broad_ENCSR810BDB.bw"
    )
)

# create a df with all dt

bw_to_df<-function(bw_path){
  all_dt = as.data.frame(import_rebin(bw_path[1],2e5,only_mcol = FALSE))[,c("seqnames","start","end")]
  
  for (idx in 1:length(bw_path)){
    bw = import_rebin(bw_path[idx],2e5,only_mcol = FALSE) # import and rebin
    
    # export the rebinned
    new_file_name = paste(tools::file_path_sans_ext(basename(bw_path[idx])),"_200kb",".bw",sep='')
    # export(bw,new_file_name)
    
    df = as.data.frame(mcols(bw))
    names(df) = names(bw_path)[idx]
    all_dt = cbind(all_dt,df)
  }
  # all_dt = all_dt[apply(all_dt[,4:11],1,prod) != 0,] # remove the rows that have at least a zero
  return(all_dt)
}

```

```{r}
#make dfs for each rep
rep1 = bw_to_df(bw_path$rep1)
rep2 = bw_to_df(bw_path$rep2)
damid = bw_to_df(bw_path$damID)
hct_hist=bw_to_df(bw_path$hct_hist)
save(col,rep1,rep2,damid,hct_hist,file = "stuff.RData")
```